### ISSUE TITLE
Install build-tools 29.0.3 on tachiyomi

### ISSUE THREAD

**Issue by brianmriley** [arkon/arkon#1]
I was getting the same error on my react native app for Android builds this morning (and it had previously worked fine for the last 6 months:

```
Couldnt find the Android build tools @ /usr/local/lib/android/sdk/build-tools/29.0.3
Unable to locate executable file: /usr/local/lib/android/sdk/build-tools/29.0.3/zipalign. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

You made the fix here:

https://github.com/tachiyomiorg/tachiyomi/commit/a9c7cbf2c43959ae7ad9df3baa2306a254dd57e3

* What led you to this solution? 
* Any idea why it started happening?
* Where is `ANDROID_SDK_ROOT` defined? 

Thanks for your help and feel free to respond to my email instead of here since it's not an issue on this repo but I needed a way to contact you.

**Comment by arkon** [comment]
See https://github.com/actions/runner-images/pull/9094

You should use a newer version; that commit wasn't really the appropriate way to solve it in that case but it worked for a quick fix without needing to validate against a newer version at the time.
